name: PT
channels:
  - pyg
  - plotly
  - openeye
  - ilastik-forge
  - pytorch
  - nvidia
  - anaconda
  - bioconda
  - psi4
  - conda-forge
  - salilab
  - http://conda.anaconda.org/openeye
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - abseil-cpp=20211102.0=h27087fc_1
  - aiohttp=3.8.1=py38h0a891b7_1
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - alembic=1.11.2=pyhd8ed1ab_0
  - ambit=0.6=py38h53dec33_2
  - anarci=2021.02.04=pyhdfd78af_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - arrow-cpp=11.0.0=h374c478_1
  - asgiref=3.7.2=pyhd8ed1ab_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - aws-c-common=0.6.8=h5eee18b_1
  - aws-c-event-stream=0.1.6=h6a678d5_6
  - aws-checksums=0.1.11=h5eee18b_2
  - aws-sdk-cpp=1.8.185=h721c034_1
  - backcall=0.2.0=pyhd3eb1b0_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.zoneinfo=0.2.1=py38h0a891b7_7
  - beautifulsoup4=4.11.1=py38h06a4308_0
  - biopython=1.81=py38h1de0b5d_0
  - blas=1.0=mkl
  - boost=1.74.0=py38h2b96118_5
  - boost-cpp=1.74.0=h75c5d50_8
  - bottleneck=1.3.5=py38h7deecbd_0
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.0=h5eee18b_0
  - ca-certificates=2025.1.31=hbcca054_0
  - cairo=1.16.0=hb05425b_5
  - catboost=1.0.4=py38h578d9bd_1
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.15.1=py38h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - chemps2=1.8.11=hbe8a562_0
  - click=8.0.4=py38h06a4308_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - cmaes=0.10.0=pyhd8ed1ab_0
  - colorlog=6.7.0=py38h578d9bd_1
  - comm=0.2.1=pyhd8ed1ab_0
  - cryptography=41.0.2=py38h22a60cf_0
  - cuda-cccl=11.8.89=0
  - cuda-command-line-tools=11.8.0=0
  - cuda-compiler=11.8.0=0
  - cuda-cudart=11.8.89=0
  - cuda-cudart-dev=11.8.89=0
  - cuda-cuobjdump=11.8.86=0
  - cuda-cupti=11.8.87=0
  - cuda-cuxxfilt=11.8.86=0
  - cuda-documentation=11.8.86=0
  - cuda-driver-dev=11.8.89=0
  - cuda-gdb=11.8.86=0
  - cuda-libraries=11.8.0=0
  - cuda-libraries-dev=11.8.0=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=11.8.86=0
  - cuda-nsight-compute=11.8.0=0
  - cuda-nvcc=11.8.89=0
  - cuda-nvdisasm=11.8.86=0
  - cuda-nvml-dev=11.8.86=0
  - cuda-nvprof=11.8.87=0
  - cuda-nvprune=11.8.86=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvrtc-dev=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-nvvp=11.8.87=0
  - cuda-profiler-api=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cuda-sanitizer-api=11.8.86=0
  - cuda-toolkit=11.8.0=0
  - cuda-tools=11.8.0=0
  - cuda-visual-tools=11.8.0=0
  - cudatoolkit=11.8.0=h6a678d5_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cytoolz=0.12.0=py38h5eee18b_0
  - dask-core=2022.7.0=py38h06a4308_0
  - dataclasses=0.8=pyhc8e2a94_3
  - datasets=2.14.3=pyhd8ed1ab_0
  - debugpy=1.8.0=py38h17151c0_1
  - decorator=5.1.1=pyhd3eb1b0_0
  - dftd3=3.2.1=h84218bc_2
  - dill=0.3.7=pyhd8ed1ab_0
  - django=4.2.6=pyhd8ed1ab_0
  - django-cors-headers=4.3.0=pyhd8ed1ab_0
  - djangorestframework=3.14.0=pyhd8ed1ab_0
  - dkh=1.2=h173d85e_2
  - exceptiongroup=1.0.4=py38h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - fancycompleter=0.9.1=py38h578d9bd_1007
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.9.0=py38h06a4308_0
  - fontconfig=2.14.1=hef1e5e3_0
  - freetype=2.10.4=hca18f0e_2
  - frozenlist=1.3.3=py38h5eee18b_0
  - fsspec=2023.6.0=pyh1a96a4e_0
  - gau2grid=2.0.7=hd18ef5c_0
  - gcp=2.0.2=he991be0_2
  - gdma=2.2.6=h0e1e685_6
  - gds-tools=1.4.0.31=0
  - gemmi=0.6.6=py38haaf2563_0
  - gflags=2.2.2=he1b5a44_1004
  - giflib=5.2.1=h5eee18b_3
  - glib=2.69.1=he621ea3_2
  - glog=0.5.0=h48cff8f_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py38heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - gplearn=0.4.2=pyhd8ed1ab_0
  - greenlet=2.0.1=py38h6a678d5_0
  - grpc-cpp=1.48.2=he1ff14a_1
  - hdf5=1.10.6=h3ffc7dd_1
  - hdf5-1107=1.10.7=0
  - hmmer=3.3.2=hdbdd923_4
  - html2text=2020.1.16=py_0
  - huggingface_hub=0.16.4=pyhd8ed1ab_0
  - icu=70.1=h27087fc_0
  - idna=3.4=py38h06a4308_0
  - imageio=2.19.3=py38h06a4308_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - importlib_resources=6.0.1=pyhd8ed1ab_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.29.0=pyhd33586a_0
  - ipython=8.12.0=py38h06a4308_0
  - jbig=2.1=h7f98852_2003
  - jedi=0.18.1=py38h06a4308_1
  - jinja2=3.1.2=py38h06a4308_0
  - joblib=1.2.0=py38h06a4308_0
  - jpeg=9e=h5eee18b_1
  - jupyter_client=8.6.0=pyhd8ed1ab_0
  - jupyter_core=5.7.1=py38h578d9bd_0
  - kiwisolver=1.4.4=py38h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcblas=3.9.0=5_h92ddd45_netlib
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcufile=1.4.0.31=0
  - libcufile-dev=1.4.0.31=0
  - libcurand=10.3.0.86=0
  - libcurand-dev=10.3.0.86=0
  - libcurl=8.1.1=h251f7ec_2
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libdeflate=1.8=h7f8727e_5
  - libecpint=1.0.7=hfebba4c_0
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h516909a_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.1.0=he5830b7_0
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libint2=2.7.1=h2fe1556_15
  - liblapack=3.9.0=5_h92ddd45_netlib
  - libllvm14=14.0.6=hcd5def8_4
  - libnghttp2=1.52.0=h2d74bed_1
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnsl=2.0.0=h7f98852_0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=3.20.3=he621ea3_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.42.0=h2797004_0
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx-ng=13.1.0=hfd8a6a1_0
  - libtasn1=4.19.0=h5eee18b_0
  - libthrift=0.15.0=h1795dd8_2
  - libtiff=4.3.0=h6f004c6_2
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxc=5.1.5=h84b9e52_1
  - libxcb=1.15=h0b41bf4_0
  - libxml2=2.9.14=h22db469_4
  - libzlib=1.2.13=hd590300_5
  - llvm-openmp=16.0.6=h4dfa4b3_0
  - llvmlite=0.40.1=py38h94a1851_0
  - locket=1.0.0=py38h06a4308_0
  - lz4-c=1.9.4=h6a678d5_0
  - mako=1.2.4=pyhd8ed1ab_0
  - marching_cubes=0.3.post9=py38_0_hb110ab7_g1a4aa17
  - markupsafe=2.1.1=py38h7f8727e_0
  - matplotlib-base=3.4.3=py38hf4fb855_1
  - matplotlib-inline=0.1.6=py38h06a4308_0
  - mctc-lib=0.3.1=hc3ea6d6_0
  - metis=5.1.0=h59595ed_1007
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - modeller=10.5=py38h9bf148f_0
  - mordred=1.2.0=py_1
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.2.0=hb012696_0
  - mpmath=1.3.0=py38h06a4308_0
  - mrcfile=1.5.0=pyhd8ed1ab_0
  - msgpack-python=1.0.3=py38hd09550d_0
  - multidict=6.0.2=py38h5eee18b_0
  - multiprocess=0.70.14=py38h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py38h06a4308_0
  - nsight-compute=2022.3.0.22=0
  - numba=0.57.1=py38hd559b08_0
  - numexpr=2.8.4=py38he184ba9_0
  - numpy=1.24.3=py38h14f4228_0
  - numpy-base=1.24.3=py38h31eccc5_0
  - ocl-icd=2.3.2=hd590300_0
  - ocl-icd-system=1.0.0=1
  - openbabel=3.1.1=py38h3d1cf2f_4
  - openeye-toolkits=2023.1.0=py38_0
  - openh264=2.1.1=h4ff587b_0
  - openmm=8.1.1=py38h10fed7f_1
  - openssl=3.3.1=hb9d3cd8_3
  - optuna=3.3.0=pyhd8ed1ab_0
  - orc=1.7.4=hb3bc3d3_1
  - ordered-set=4.1.0=pyhd8ed1ab_0
  - packaging=23.0=py38h06a4308_0
  - pandas=1.5.3=py38h417a72b_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.2.0=pyhd3eb1b0_1
  - pcmsolver=1.2.1.1=py38h6d17ec8_2
  - pcre=8.45=h9c3ff4c_0
  - pdbfixer=1.9=pyh1a96a4e_0
  - pdbpp=0.10.3=pyhd8ed1ab_0
  - pebble=5.0.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.4.0=py38h6a678d5_0
  - pint=0.17=pyhd8ed1ab_0
  - pip=23.2.1=py38h06a4308_0
  - pixman=0.40.0=h36c2ea0_0
  - platformdirs=4.2.0=pyhd8ed1ab_0
  - plotly=5.16.1=py_0
  - pluggy=1.0.0=py38h06a4308_1
  - polars=0.18.11=py38h0cc4f7c_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.36=py38h06a4308_0
  - psi4=1.6.1+5b9f6e3=py38h1bd450f_0
  - psutil=5.9.0=py38h5eee18b_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-cpuinfo=9.0.0=py38h06a4308_0
  - pyarrow=11.0.0=py38h992f0b0_0
  - pycairo=1.24.0=py38h1a1917b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=1.10.12=py38h5eee18b_1
  - pyg=2.3.1=py38_torch_2.0.0_cu118
  - pygments=2.15.1=py38h06a4308_1
  - pylatex=1.4.1=pyh9f0ad1d_0
  - pynndescent=0.5.10=pyh1a96a4e_0
  - pyopenssl=23.2.0=py38h06a4308_0
  - pyparsing=3.0.9=py38h06a4308_0
  - pyqtgraph=0.13.1=py38h06a4308_0
  - pyrepl=0.9.0=py38h01eb140_9
  - pysocks=1.7.1=py38h06a4308_0
  - pytest=7.4.0=py38h06a4308_0
  - python=3.8.17=he550d4f_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-xxhash=2.0.2=py38h5eee18b_1
  - python_abi=3.8=2_cp38
  - pytorch=2.0.1=py3.8_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - pytz=2023.3=pyhd8ed1ab_0
  - pywavelets=1.4.1=py38h5eee18b_0
  - pyyaml=6.0=py38h0a891b7_4
  - pyzmq=25.1.2=py38h34c975a_0
  - qcelemental=0.25.1=pyhd8ed1ab_1
  - qcengine=0.24.1=pyhd8ed1ab_0
  - re2=2022.04.01=h27087fc_0
  - readline=8.2=h5eee18b_0
  - regex=2022.7.9=py38h5eee18b_0
  - reportlab=3.6.12=py38h5eee18b_0
  - sacremoses=0.0.53=pyhd8ed1ab_0
  - scikit-image=0.19.3=py38h6a678d5_1
  - scikit-learn=1.3.0=py38h1128e8f_0
  - scikit-sparse=0.4.12=py38hf34f610_0
  - scipy=1.10.1=py38h14f4228_0
  - seaborn=0.12.2=py38h06a4308_0
  - setuptools=68.0.0=py38h06a4308_0
  - shap=0.43.0=py38h53bb729_0
  - simint=0.7=h642920c_1
  - six=1.16.0=pyhd3eb1b0_1
  - slicer=0.0.7=pyhd8ed1ab_0
  - snappy=1.1.9=h295c915_0
  - soupsieve=2.3.2.post1=py38h06a4308_0
  - sqlalchemy=2.0.19=py38h01eb140_0
  - sqlite=3.41.2=h5eee18b_0
  - sqlparse=0.4.4=pyhd8ed1ab_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - suitesparse=5.10.1=h9e50725_1
  - sympy=1.11.1=py38h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tenacity=8.2.2=py38h06a4308_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tifffile=2020.10.1=py38hdd07704_2
  - timeout-decorator=0.5.0=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - tokenizers=0.13.3=py38h22610ee_0
  - tomli=2.0.1=py38h06a4308_0
  - toolz=0.12.0=py38h06a4308_0
  - torchaudio=2.0.2=py38_cu118
  - torchtriton=2.0.0=py38
  - torchvision=0.15.2=py38_cu118
  - tornado=6.3.2=py38h01eb140_0
  - tqdm=4.65.0=py38hb070fc8_0
  - traitlets=5.7.1=py38h06a4308_0
  - transformers=4.28.1=pyhd8ed1ab_0
  - typing-extensions=4.7.1=py38h06a4308_0
  - typing_extensions=4.7.1=py38h06a4308_0
  - tzdata=2023c=h71feb2d_0
  - umap-learn=0.5.3=py38h578d9bd_1
  - urllib3=1.26.16=py38h06a4308_0
  - utf8proc=2.6.1=h27cfd23_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.38.4=py38h06a4308_0
  - wmctrl=0.5=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xtb=6.5.1=h97a9613_0
  - xxhash=0.8.0=h7f98852_3
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.7.2=py38h0a891b7_2
  - zeromq=4.3.5=h59595ed_0
  - zipp=3.16.2=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zlib-ng=2.0.7=h0b41bf4_0
  - zstd=1.5.2=h8a70e8d_1
  - pip:
      - anyio==4.3.0
      - cairocffi==1.6.1
      - cairosvg==2.7.1
      - commonmark==0.9.1
      - cssselect2==0.7.0
      - defusedxml==0.7.1
      - distro==1.9.0
      - docker==6.1.3
      - e3nn==0.5.6
      - egnn-pytorch==0.2.8
      - einops==0.8.1
      - ete3==3.1.3
      - evaluate==0.4.0
      - future==1.0.0
      - h11==0.14.0
      - hjson==3.1.0
      - httpcore==1.0.3
      - httpx==0.26.0
      - ipdb==0.13.13
      - lapy==1.0.1
      - levenshtein==0.25.1
      - logomaker==0.8.7
      - mlrose-hiive==2.2.4
      - nibabel==5.1.0
      - ninja==1.11.1
      - nvidia-nccl-cu12==2.25.1
      - openai==1.12.0
      - opt-einsum==3.4.0
      - opt-einsum-fx==0.1.4
      - pdb-tools==2.5.0
      - pmx==0+untagged.884.g98fbe40
      - protobuf==4.24.3
      - pybiolib==1.1.1264
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.16
      - pyqt5-sip==12.15.0
      - python-levenshtein==0.25.1
      - rapidfuzz==3.9.7
      - rdkit==2023.9.5
      - requests==2.29.0
      - responses==0.18.0
      - rich==12.6.0
      - rpg==2.0.1
      - sentencepiece==0.1.99
      - smml==0.1.0
      - sniffio==1.3.0
      - tinycss2==1.2.1
      - webencodings==0.5.1
      - websocket-client==1.6.2
      - xgboost==2.1.3
prefix: /home/EJP/anaconda3/envs/PT
